export const MENU = [
    "Información general: convalidaciones, exenciones y títulos",
    "1.- Solicitud de convalidaciones",
    "1.1.- Convalidaciones en FP",
    "1.1.1.- ¿Qué necesito para poder convalidar?",
    "1.1.2.- ¿Qué estudios puedo alegar?",
    "1.2.- ¿Dónde encontrar qué módulos son convalidables?",
    "1.2.1.- Condiciones para convalidar FOL",
    "1.2.2.- Condiciones para convalidar Empresa e Iniciativa Emprendedora",
    "1.2.3.- Condiciones para convalidar Inglés",
    "1.2.4.- Condiciones para convalidar Segunda Lengua Extranjera",
    "1.2.5.- Condiciones para convalidar las Horas de Libre Configuración",
    "1.2.6.- Condiciones para convalidar el módulo de Proyecto",
    "1.2.7.- Exención de la FCT",
    "1.3.- ¿Puedo convalidar un módulo acreditando experiencia laboral?",
    "1.4.- ¿Qué organismo resuelve las convalidaciones?",
    "1.5.- ¿Qué documentación debo enviar al centro?",
    "1.6.- ¿Cómo conseguir el programa de una asignatura universitaria?",
    "1.7.- ¿Cómo saber si me convalidarán un módulo si he alegado estudios universitarios?",
    "1.8.- ¿Cuándo tendré noticias sobre si se ha aprobado la convalidación?",
    "1.9.- ¿Qué efectos tendrá la convalidación en mi expediente?",
    "1.10.- Enlaces relacionados",
    "2.- Solicitud del título",
    "2.1.- Solicitud",
    "2.2.- Tramitación y recogida",
    "Historial de versiones",
]

export const HOME = {
    titulo: "Información general: convalidaciones, exenciones y títulos.",
    p1: "Antes de empezar debemos aclarar la diferencia entre convalidación, exención y traslado de calificación. La convalidación es el procedimiento por el cual se reconoce como superado un módulo que contiene los contenidos del módulo, módulos profesionales, asignatura o unidad de competencia que se aporta. La exención solo se aplica al módulo profesional de formación en centros de trabajo y se debe aportar una experiencia profesional acreditable y de duración definida. El traslado de calificaciones es la calificación que se asigna a un módulo que posee el mismo código y denominación que otro ya cursado y superado.",
    p2: "A continuación, se muestra información tutorial que esperamos que te sea de utilidad.",
    elaboradoTitulo: "Elaborado por:",
    elaboradoContenido: "Dirección General de Formación Profesional",
    versionTitulo: " Versión:",
    versionContenido: "5",
    fechaTitulo: "Fecha de publicación:",
    fechaContenido: "3/03/2022",
    imgLink1: "Woof ",
    imgLink2: " tutor and student"
}

export const PAGE1 = {
    titulo: "1.- Solicitud de convalidaciones",
    parrafo: "Aquí encontrarás información acerca de cómo solicitar la convalidación de un módulo profesional y la exención del módulo de Formación en Centros de Trabajo.",
    imgLink: "Balanza"
}

export const PAGE1_1 = {
    titulo: "1.1.- Convalidaciones en FP",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Claude star",
    imgLink5: " bajo ",
    imgLink6: "CC",
    parrafo1: "La Subdirección General de Ordenación e Innovación de la Formación Profesional del Ministerio de Educación y Formación Profesional, informa que ",
    parrafoBold1: "el plazo de presentación de solicitudes de convalidaciones de los alumnos en el centro se inicia el día que comienza el curso escolar y finaliza el último día del curso escolar.",
    parrafo2: " Tratándose con preferencia los expedientes presentados desde el inicio del plazo de matriculación hasta la finalización del mes de octubre.",
    parrafo3: "Este plazo es revisado de forma estricta por el Ministerio acogiéndose al Real Decreto 1085/2020, de 9 de diciembre, por el que se establecen convalidaciones de módulos profesionales de los títulos de Formación Profesional del sistema educativo español y las medidas para su aplicación, y se modifica el Real Decreto 1147/2011, de 29 de julio, por el que se establece la ordenación general de la formación profesional del sistema educativo, regula en su Capítulo II  el Procedimiento para las convalidaciones.",
    parrafo4: "Por todo ello, ",
    parrafoBold2: "os informamos a todas aquellas personas que deseen solicitar una convalidación que sea competencia del Ministerio de Educación que envíe la documentación en el plazo más breve de tiempo posible con el fin de comprobar la ausencia de errores y así poder iniciar el trámite lo antes posible.",
    parrafo5: "Las solicitudes de convalidaciones cuya resolución corresponden al director/a del centro docente donde esté matriculado el alumno se presentarán durante el mes de octubre.",
    parrafoBold3: "Solo se podrá presentar una única solicitud de convalidación por curso académico.",
    parrafoBold4: "ES MUY IMPORTANTE QUE TODA LA DOCUMENTACIÓN SEA CORRECTA Y ESTÉ COMPLETA."
}

export const PAGE1_1_1 = {
    titulo: "1.1.1.- ¿Qué necesito para poder convalidar?",
    parrafo1: "La primera condición:",
    parrafo2: "Si eres alumno de SEMI o distancia: ",
    parrafoBold1: "estar matriculado/a en el módulo que se desea convalidar",
    parrafo3: " y realizar el pago de las tasas correspondientes. Hasta que no se realice y se compruebe el pago, no se podrá ejecutar la convalidación en el expediente. De esta forma, si el pago se retrasa cabría la posibilidad de que la resolución de la convalidación también se retrasara.",
    parrafo4: "La ",
    parrafoBold2: "convalidación no se realiza sobre la globalidad del Título",
    parrafo5: " que se está cursando, sino sobre los módulos que se soliciten, si estos cumplen las condiciones para ello."
}

export const PAGE1_1_2 = {
    titulo: "1.1.2.- ¿Qué estudios puedo alegar?",
    parrafo1: "Para solicitar la convalidación de módulos profesionales de un ciclo formativo de FP ",
    parrafoBold1: "se pueden alegar enseñanzas",
    parrafo2: " cursadas dentro ",
    parrafoBold2: "del Sistema Educativo",
    parrafo3: " y Unidades de Competencia acreditadas. Por tanto, se puede aportar:",
    parrafoBold3: "Otros ciclos formativos",
    parrafo4: " de Formación Profesional de grado medio o superior cursados con anterioridad.",
    parrafoBold4: "Enseñanzas universitarias:",
    parrafo5: " diplomaturas, licenciaturas, grados.",
    parrafo6: "Las ",
    parrafoBold5: "antiguas enseñanzas de Formación Profesional",
    parrafo7: " de primer y segundo grado (títulos de Técnico auxiliar y Técnico especialista).",
    parrafo8: "Ciclos formativos de ",
    parrafoBold6: "Enseñanzas deportivas",
    parrafo9: " o de ",
    parrafoBold7: "Artes Plásticas y Diseño.",
    parrafo10: "Certificaciones académicas Oficiales de idioma (del mismo idioma que se solicita la convalidación y de nivel idóneo).",
    parrafo11: "Unidades de Competencia acreditadas.",
    parrafo12: "Las enseñanzas siguientes no se pueden alegar:",
    parrafoBold8: "Carnés profesionales y cursos de Formación Profesional para el empleo (FPO y FP continua)",
    parrafo13: ", distintos de los que conducen a la obtención de un ",
    parrafoItalic1: "Certificado de profesionalidad",
    parrafo14: " y a la acreditación oficial de unidades de competencia.",
    parrafoBold9: "Cursos privados",
    parrafo15: " realizados en academias y centros de formación que no imparten enseñanzas oficiales.",
    parrafoBold10: "Cursos propios impartidos en la Universidad",
    parrafo16: ", que no sean másteres oficiales como los cursos de experto, cursos de especialización, ...",
    parrafoBold11: "Títulos propios no oficiales de universidad.",
    parrafoBold12: "Certificados de idiomas no oficialmente aceptados.",
    parrafoBold13: "Experiencia laboral.",
    parrafoBold14: "Formación no formal.",
    parrafoBold15: "Titulaciones extranjeras homologadas.",
    parrafoBold16: "Títulos equivalentes LOGSE.",
    parrafoBold17: "Formaciones de otros ministerios que tienen concedida por normativa la equivalencia general o específica.",
    parrafo17: "Los ",
    parrafoBold18: "módulos profesionales",
    parrafo18: " que ",
    parrafoBold19: "hayan sido previamente convalidados no podrán ser alegados para convalidar.",
    parrafo19: " Solo se puede alegar materias que hayan sido cursadas y superadas. Los títulos extranjeros homologados tampoco podrán ser causa de una nueva convalidación con otros módulos profesionales.",
    parrafo20: "Los ",
    parrafoBold20: "estudios que tengan concedida la equivalencia específica o genérica ",
    parrafoBold21: "(aquí los tenéis)",
    parrafo21: ", a efectos académicos y/o profesionales, con títulos de Formación Profesional ",
    parrafoBold22: "no podrán ser utilizados a su vez para la convalidación de sus módulos profesionales",
    parrafo22: "; por tanto, quien haya superado la totalidad de un ciclo formativo LOGSE no podrá aportarlo para solicitar la convalidación de ningún módulo profesional del título LOE equivalente que lo sustituye. Las convalidaciones que aparecen recogidas en el anexo IV del Real Decreto que regula cada título están reservadas para quien no ha podido finalizar el ciclo formativo que se extingue y debe transitar al nuevo ciclo formativo equivalente, o para quien solicita dichas convalidaciones para un título diferente de aquel con el que se ha declarado la equivalencia.",
    parrafo23: "Haber cursado enseñanzas superiores no siempre da derecho a la convalidación de enseñanzas relacionadas, pero de menor nivel, aunque en ambas haya materias con nombres similares.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Escolaespai",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_2 = {
    titulo: "1.2.- ¿Dónde encontrar qué módulos son convalidables?",
    p1: "Son dos los documentos que debes consultar:",
    p2: "Por un lado, los diferentes ",
    pBold1: "Anexos del ",
    pBold2: "Real Decreto ",
    pItalic1: "1085/2020, de 9 de diciembre, por el que se establecen convalidaciones de módulos profesionales de los títulos de Formación Profesional del sistema educativo español y las medidas para su aplicación, y se modifica el Real Decreto 1147/2011, de 29 de julio, por el que se establece la ordenación general de la formación profesional del sistema educativo.",
    p3: " Aquí puedes consultar las tablas de convalidaciones del Real decreto 1085/2020, de 9 de diciembre (",
    p4: "tablas de convalidación",
    p5: ").",
    p6: "Por otro, el ",
    pBold3: "Anexo IV del Real Decreto",
    p7: " que crea el título LOE que estás estudiando, ya que establece las convalidaciones con módulos LOGSE del mismo Ciclo. Quien haya superado la totalidad de un ciclo formativo LOGSE no podrá aportarlo para solicitar la convalidación de ningún módulo profesional del ciclo formativo LOE que lo sustituye. Estas convalidaciones están reservadas para quien transita a un ciclo formativo LOE desde un ciclo formativo LOGSE, sin haberlo finalizado ni obtenido el título.",
    p8: "Ten en cuenta que los ",
    pBold4: "módulos profesionales con el mismo código y denominación",
    p9: " presentes en diferentes ciclos formativos LOE ",
    pBold5: "son en realidad el mismo módulo profesional.",
    p10: " Estos módulos se denominan ",
    pBold6: "transversales.",
    p11: " Si superas un módulo profesional transversal en un ciclo formativo, lo tendrás superado en cualquier otro del que también forme parte y ",
    pBold7: "la calificación obtenida se traslada de un ciclo al otro sin necesidad de convalidación ni más trámite.",
    p12: "Los módulos profesionales de FOL y EIE tienen en todos los ciclos formativos LOE la misma denominación, pero diferentes códigos. Por tanto, no hay arrastre de calificación sino convalidación. Se deben cursar o convalidar de un ciclo formativo a otro (siempre que se cumplan los requerimientos para ello).",
    p13: "La convalidación del módulo FOL puedes consultarla en el siguiente enlace: ",
    p14: "Convalidación de FOL",
    p15: ".",
    p16: "La convalidación del módulo EIE puedes consultarla en el siguiente enlace: ",
    p17: "Convalidación de EIE",
    p18: ".",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "MonikaP",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_2_1 = {
    titulo: "1.2.1-. Condiciones para convalidar FOL",
    p1: "Para poder convalidar el módulo de FOL (Formación y Orientación Laboral) es necesario acreditar alguna de las siguientes condiciones:",
    p2: "Si el módulo a convalidar pertenece a un ciclo LOE (Ley Orgánica 2/2006, de 3 de mayo). ",
    pBold1: "Para esta convalidación es indiferente que los módulos que se aporten sean de grado medio o superior.",
    pBold2: "Tener aprobado el módulo de FOL en cualquier otro Ciclo LOE y acreditarlo documentalmente.",
    pBold3: "Tener aprobado el módulo de FOL en un Ciclo LOGSE (Ley Orgánica 1/1990, de 3 de octubre) y poseer un certificado que acredite que se posee la formación establecida para el desempeño de las funciones de nivel básico de la actividad preventiva",
    p3: " (PRL). Sirve cualquier curso de PRL impartido por alguna entidad legalmente constituida, de una duración no inferior a 30 horas y cuyos contenidos incluyan los que indica el anexo IV del Real Decreto 39/1997, de 17 de enero (BOE de 31 de enero de 1997), por el que se aprueba el Reglamento de los Servicios de Prevención. ",
    pBold4: "El certificado del curso de PRL deberá hacer constar específicamente tanto la duración como los contenidos impartidos.",
    pBold5: "Poseer el título de Técnico Superior en Prevención de Riesgos Profesionales derivado de la Ley Orgánica 1/1990, de 3 de octubre.",
    p4: "Si el módulo a convalidar pertenece a un ciclo LOGSE de grado medio (Ley Orgánica 1/1990, de 3 de octubre):",
    pBold6: "Tener aprobado el módulo de FOL en un Ciclo LOGSE (Ley Orgánica 1/1990, de 3 de octubre).",
    pBold7: "Tener aprobado el módulo de FOL en cualquier otro Ciclo LOE y acreditarlo documentalmente.",
    p5: "Si el módulo a convalidar pertenece a un ciclo LOGSE de grado superior (Ley Orgánica 1/1990, de 3 de octubre):",
    pBold8: "Tener aprobado el módulo de FOL en un Ciclo LOGSE de Grado Superior (Ley Orgánica 1/1990, de 3 de octubre).",
    table1: "Módulo a convalidar",
    table2: "Formación a aportar",
    table3: "FOL GM (LOGSE Ley Orgánica 1/1990, de 3 de octubre)",
    table4: "FOL GM LOGSE",
    table5: "FOL GS LOGSE",
    table6: "FOL GM LOE",
    table7: "FOL GS LOE",
    table8: "FOL GS (LOGSE Ley Orgánica 1/1990, de 3 de octubre)",
    table9: "FOL GS LOGSE",
    table10: "FOL GM (LOE Ley Orgánica 2/2006, de 3 de mayo)",
    table11: "FOL GM LOE",
    table12: "FOL GS LOE",
    table13: "FOL GM LOGSE + Certificado nivel básico actividad preventiva",
    table14: "FOL GS LOGSE + Certificado nivel básico actividad preventiva",
    table15: "Título Técnico Superior en Prevención de Riesgos Profesionales",
    table16: "FOL GS (LOE Ley Orgánica 2/2006, de 3 de mayo)",
    table17: "FOL GM LOE",
    table18: "FOL GS LOE",
    table19: "FOL GM LOGSE + Certificado nivel básico actividad preventiva",
    table20: "FOL GS LOGSE + Certificado nivel básico actividad preventiva",
    table21: "Título Técnico Superior en Prevención de Riesgos Profesionales"
}

export const PAGE1_2_2 = {
    titulo: "1.2.2.- Condiciones para convalidar Empresa e Iniciativa Emprendedora",
    p1: "Para poder convalidar el módulo de ",
    pBold1: "Empresa e Iniciativa Emprendedora",
    p2: " es necesario acreditar alguna de las siguientes condiciones:",
    p3: "Tener ",
    pBold2: "aprobado el módulo de Empresa e Iniciativa Emprendedora de otro ciclo formativo",
    p4: ", cualquiera que sea el grado, incluso en grados cruzados -medio o superior-.",
    p5: "Tener ",
    pBold3: "aprobado el módulo de Administración, gestión y comercialización en la pequeña empresa",
    p6: " (o con una denominación similar).",
    pBold4: "Poseer el Título de Técnico en Gestión administrativa o Técnico superior en Administración y finanzas.",
    table1: "Módulo a convalidar",
    table2: "Formación a aportar",
    table3: "Empresa e Iniciativa Emprendedora. (Cualquier ciclo formativo)",
    table4: "Administración, gestión y comercialización en la pequeña empresa. (Cualquier ciclo formativo)",
    table5: "Administración y gestión de un pequeño establecimiento comercial. Ciclo Comercio. (Comercio y Marketing)",
    table6: "Organización y gestión de una explotación agraria familiar Ciclo Trabajos Forestales y de Conservación del Medio Natural. (RD 1713/1996, de 12 de julio). (Agraria) Ciclo Jardinería. (RD 1714/1996, de 12 de julio). (Agraria) Ciclo Explotaciones Agrarias Extensivas. (RD 1715/1996, de 12 de julio) (Agraria) Ciclo Explotaciones Agrícolas Intensivas. (RD 1716/1996, de 12 de julio). (Agraria) Ciclo Explotaciones Ganaderas. (RD 1717/1996, de 12 de julio).  (Agraria)",
    table7: "Ciclo completo de Gestión administrativa. (RD 1662/1994, de 22 de julio). (Administración y Gestión)",
    table8: "Administración, gestión y comercialización en la pequeña empresa. (Cualquier ciclo formativo)",
    table9: "Organización y gestión de una pequeña empresa de actividades de tiempo libre y socioeducativas. Ciclo Animación Sociocultural. (Servicios Socioculturales y a la Comunidad) Ciclo Animación de Actividades Físicas y Deportivas. (Actividades Físicas y Deportivas) Ciclo Animación Turística. (Hostelería y Turismo)",
    table10: "Organización y control en agencias de viajes. Ciclo Agencias de Viajes. (Hostelería y Turismo)",
    table11: "Administración de establecimientos de restauración. Ciclo Restauración. (Hostelería y Turismo)",
    table12: "Administración y gestión de una unidad/gabinete de Ortoprotésica. Ciclo Ortoprotésica. (Sanidad)",
    table13: "Organización, administración y gestión de una unidad/gabinete de prótesis dentales. Ciclo Prótesis Dentales. (Sanidad)",
    table14: "Administración y gestión de un gabinete audioprotésico. Ciclo Audioprótesis. (Sanidad)",
    table15: "Organización y gestión de una empresa agraria. Ciclo Gestión y Organización de los Recursos Naturales y Paisajísticos. (Agraria) Ciclo Gestión y Organización de Empresas Agropecuarias. (Agraria)",
    table16: "Ciclo completo de Administración y finanzas. (RD 1659/1994, de 22 de julio). (Administración y Gestión)",
    table17: "Técnico en Gestión Administrativa LOE.  Ciclo completo",
    table18: "Técnico en Superior en Administración y Finanzas LOE. Ciclo completo",
    table19: "0402. Empresa e iniciativa emprendedora.",
    table20: "Gestión económico-administrativa en agencias de viajes. Organización y control en agencias de viajes.",
    table21: "0863. Empresa e iniciativa emprendedora.",
    table22: "Organización, administración y gestión de una unidad/gabinete de prótesis dentales.",
    table23: "Empresa e Iniciativa Emprendedora. (Cualquier ciclo formativo LOE)",
    table24: "Empresa e Iniciativa Emprendedora. (Cualquier ciclo formativo LOE)"
}

export const PAGE1_2_3 = {
    titulo: "1.2.3.- Condiciones para convalidar Inglés",
    p1: "La documentación a aportar varía en función del módulo Inglés que se desee convalidar. Siempre deben ser estudios cursados y superados de lengua inglesa.",
    table1: "Módulo a convalidar",
    table2: "Formación a aportar",
    table3: "0156 Inglés",
    table4: "Lengua Extranjera LOGSE (duración de 65 horas, según el Real Decreto que establece el título de formación profesional y sus enseñanzas mínimas) Cuando la lengua extranjera cursada y superada sea inglés.",
    table5: "Lengua Extranjera LOGSE o de la C.A. Cuando la lengua extranjera cursada y superada sea inglés",
    table6: "Módulos Profesionales de Lengua Extranjera LOGSE de ciclos formativos de Grado Superior, en cualquiera de sus denominaciones, siempre que sea la misma que la que se desea convalidar.",
    table7: "Certificado del Ciclo Elemental, de Inglés, de la Escuela Oficial de Idiomas. (RD 967/1988, de 2 de septiembre).",
    table8: "Certificado de Nivel Intermedio (B1), de Inglés, de la Escuela Oficial de Idiomas. (RD 1629/2006, de 29 de diciembre).",
    table9: "Certificado de Aptitud de Inglés de la Escuela Oficial de Idiomas. (RD 967/1988, de 2 de septiembre).",
    table10: "Certificado de Nivel Avanzado (B2), o superior, de Inglés de la Escuela Oficial de Idiomas. (RD 1629/2006, de 29 de diciembre).",
    table11: "Título de Grado, o equivalente, en Filología Inglesa.",
    table12: "Título de Grado, o equivalente, en Traducción e Interpretación (Inglés).",
    table13: "0179 Inglés.",
    table14: "0179 Inglés",
    table15: "Lengua Extranjera LOGSE (Inglés).",
    table16: "Lengua Extranjera (duración de 90 horas, según reales decretos por los que se establecen los títulos de formación profesional y sus enseñanzas mínimas) Cuando la lengua extranjera cursada y superada sea inglés",
    table17: "Lengua Extranjera en Comercio Internacional. Cuando la lengua extranjera cursada y superada sea inglés.",
    table18: "Certificado de Aptitud de Inglés de la Escuela Oficial de Idiomas. (RD 967/1988, de 2 de septiembre).",
    table19: "Certificado de Nivel Avanzado (B2), o superior, de Inglés de la Escuela Oficial de Idiomas. (RD 1629/2006, de 29 de diciembre).",
    table20: "Título de Grado, o equivalente, en Filología Inglesa",
    table21: "Título de Grado, o equivalente, en Traducción e Interpretación (Inglés).",
    pBold1: "Para saber más",
    p2: "Por tanto, no es posible, ",
    pBold2: "EN NINGÚN CASO",
    p3: ", convalidar este módulo por haber cursado una asignatura universitaria relativa a este idioma."
}

export const PAGE1_2_4 = {
    titulo: "1.2.4.- Condiciones para convalidar Segunda Lengua Extranjera",
    p1: "Para poder convalidar el módulo de Segunda Lengua Extranjera debe aportarse siempre estudios cursados y superados en la misma lengua que se desee convalidar. Es necesario acreditar alguna de las siguientes condiciones:",
    table1: "Módulo a convalidar",
    table2: "Formación a aportar",
    table3: "2ª Lengua Extranjera LOGSE",
    table4: "MP Segunda Lengua Extranjera LOGSE, siempre que sea la misma que la que se desea convalidar.",
    table5: "Certificado de Nivel Intermedio (B1), equivalente o superior, de la Escuela Oficial de Idiomas (RD 1629/2006, de 29 de diciembre) siempre que sea de la misma lengua extranjera que la que se desea convalidar.",
    table6: "Título de Grado en Filología o equivalente, de la misma especialidad que la lengua extranjera que se desea convalidar.",
    table7: "Título de Grado Traducción e Interpretación, o equivalente, de la misma especialidad que la lengua extranjera que se desea convalidar.",
    table8: "0180 2ª Lengua Extranjera.",
    table9: "Segunda Lengua Extranjera LOGSE. Cuando la lengua extranjera cursada y superada sea la misma que se desea convalidar.",
    table10: "Certificado del Ciclo Elemental o de Aptitud, de la Escuela Oficial de Idiomas. (RD 967/1988, de 2 de septiembre). (De la misma lengua extranjera que se desea convalidar).",
    table11: "Certificado de Nivel Intermedio (B1), o superior, de la Escuela Oficial de Idiomas. (RD 1629/2006, de 29 de diciembre). (De la misma lengua extranjera que se desea convalidar).",
    table12: "Título de Grado, o equivalente, en Filología o en Traducción e Interpretación. (De la misma especialidad que la lengua extranjera que se desea convalidar).",
    p2: "Por tanto, no es posible, ",
    pBold1: "EN NINGÚN CASO",
    p3: ", convalidar este módulo por haber cursado una asignatura universitaria relativa a este idioma."
}

export const PAGE1_2_5 = {
    titulo: "1.2.5.- Condiciones para convalidar las Horas de Libre Configuración",
    p1: "El módulo profesional de ",
    pBold1: "Horas de Libre Configuración no puede ser objeto de convalidación.",
    p2: "Este módulo profesional no se evalúa de manera independiente al estar asociado a otro módulo profesional a efectos de evaluación. Cuando un alumno o alumna obtiene la convalidación de este otro módulo profesional (o lo haya superado con anterioridad), queda exento de cursar el de Horas de Libre Configuración."
}

export const PAGE1_2_6 = {
    titulo: "1.2.6.- Condiciones para convalidar el módulo de Proyecto",
    p1: "El módulo profesional de Proyecto correspondiente a títulos de Formación profesional de grado superior no podrá ser objeto de convalidación ni de exención en ningún caso."
}

export const PAGE1_2_7 = {
    titulo: "1.2.7.- Exención de la FCT",
    p1: "El módulo profesional de Formación en Centros de Trabajo nunca será susceptible de convalidación, sino de exención total o parcial. Se podrá calificar como exento por correspondencia total o parcial con la experiencia laboral demostrable relacionada con los estudios profesionales respectivos. Para ello se requiere la matriculación previa del alumno en el módulo.",
    p2: "Se debe acreditar, tanto para la exención total como para la parcial, una experiencia laboral equivalente al trabajo a tiempo completo de, al menos, un año, que permita demostrar que la persona solicitante tiene adquiridos los resultados de aprendizaje del módulo profesional de formación en centros de trabajo. En el caso de contratos a tiempo parcial, los días de cotización deberán ser equivalentes a un año a tiempo completo.",
    p3: "Para solicitar la exención de la FCT ",
    pBold1: "deberás enviar por correo certificado, y preferiblemente con acuse de recibo, a la atención de la Dirección de tu centro",
    p4: " lo siguiente:",
    pBold2: "Anexo I",
    p5: " (solicitud de exención) de la Orden de 28 de septiembre de 2011, por la que se regulan los módulos profesionales de formación en centros de trabajo y de proyecto para el alumnado matriculado en centros docentes de la Comunidad Autónoma de Andalucía. ",
    p6: "Puedes obtener aquí el impreso solicitud exención FCT",
    p7: ".",
    pBold3: "Documentación acreditativa",
    p8: " que justifique la experiencia laboral.",
    pBold4: "Información sobre la exención de la FCT:",
    p9: 'Apartado "¿Cómo se solicita la exención del módulo profesional de Formación en Centros de Trabajo (FCT)?", en el siguiente enlace: ',
    p10: "Convalidaciones entre módulos profesionales"
}

export const PAGE1_3 = {
    titulo: "1.3.- ¿Puedo convalidar un módulo acreditando experiencia laboral?",
    pBold1: "Salvo el módulo de Formación en Centros de Trabajo ",
    pItalic1: '(las "prácticas")',
    pBold2: ", la respuesta es no.",
    p1: " En general, ",
    pBold3: "no es posible convalidar un módulo acreditando experiencia laboral a través de un informe de vida laboral.",
    p2: "Si alguna persona cree que con su experiencia profesional ha adquirido las competencias necesarias de un módulo concreto, debe acreditar la posesión de esas unidades de competencia bien mediante un ",
    pBold4: "certificado de profesionalidad",
    p3: " o bien porque ha participado en un ",
    pBold5: "procedimiento de acreditación de competencias profesionales",
    p4: " y así se lo han reconocido, ",
    pUnderline1: "no a través de un certificado de vida laboral",
    p5: ". ",
    pBold6: "Tampoco serán válidos los resguardos de haber solicitado el certificado de profesionalidad, los diplomas o certificados de asistencia expedidos por el centro o entidad de formación u otros documentos justificativos distintos de los indicados.",
    p6: " Estas convalidaciones se regulan en el anexo V.A del Real Decreto que crea el título que se está estudiando (en este anexo se indican las unidades de competencia que se adquieren al superar cada módulo profesional).",
    p7: "Por tanto, ",
    pBold7: "las unidades de competencia debidamente acreditadas pueden ser aportadas para solicitar la convalidación de módulos profesionales según lo regulado en el anexo V.A del Real Decreto",
    p8: " que regula cada título siempre que se aporte el ",
    pBold8: "certificado de profesionalidad",
    p9: " o la ",
    pBold9: "certificación oficial de la acreditación de la Unidad de Competencia.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Voltamax",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_4 = {
    titulo: "1.4.- ¿Qué organismo resuelve las convalidaciones?",
    p1: "Las convalidaciones recogidas expresamente en los ",
    pBold1: "diferentes Anexos del ",
    pBold2: "RD 1085/2020, de 9 de diciembre",
    p2: " las resuelve la dirección del centro donde esté matriculado el alumno/a. Se ",
    pBold3: "resolverá negativamente aquellas solicitudes de su competencia que no aparezcan en los anexos anteriormente citados.",
    p3: "Aquellas solicitudes que acrediten para convalidar ",
    pBold4: "una titulación universitaria o un título de FP1 o FP2",
    p4: " las resuelve el ",
    pBold5: "Ministerio de Educación y Formación Profesional",
    p5: ". Estas últimas convalidaciones se envían al centro y se trasladan al Ministerio. ",
    pBold6: "En ningún caso el alumnado podrá enviar directamente la solicitud de convalidación al Ministerio."
}

export const PAGE1_5 = {
    titulo: "1.5.- ¿Qué documentación debo enviar al centro?",
    p1: "Debes presentar la solicitud de convalidación de módulos profesionales, acompañada de la documentación establecida correspondiente, en el centro. ",
    pBold1: "En ningún caso puedes enviar por tu cuenta la solicitud al Ministerio.",
    pBold2: "Solicitud de convalidación",
    p2: " que encuentras en este ",
    pBold3: 'enlace (ver "Impreso solicitud convalidación módulos profesionales")',
    p3: ". En ese documento es imprescindible que cumplimentes todos los apartados. En este ",
    pBold4: "enlace",
    p4: " puedes consultar los módulos de cada ciclo impartido con ",
    pBold5: 'su nombre y el código exacto. Para ello, debes desplegar dentro de cada centro, el apartado "Módulos ofertados de este ciclo". Recuerda que el plazo para enviar la solicitud de convalidación concluye a finales de octubre.',
    pBold6: "Fotocopia del Documento Nacional de Identidad",
    p5: " (DNI) o fotocopia del Pasaporte o de la Tarjeta de Extranjero/a o del Permiso de Residencia (temporal o definitivo) o del Visado de Estudios.",
    p6: "Además, debe incluirse la siguiente documentación, ",
    pBold7: "ya sea original o fotocopia compulsada",
    p7: " (recuerda que puedes compulsar un documento en cualquier Administración Pública que cuente con registro simplemente presentando la copia y enseñando el original):",
    pBold8: "Certificación académica oficial expedida por el centro docente donde has cursado los estudios que alegas",
    p8: ". En el caso de estudios universitarios, es obligatorio presentar original o fotocopia compulsada de la certificación académica oficial, con indicación de las horas o créditos de cada materia superada.",
    pBold9: "En el caso de alegar un título que acredite la formación previa alegada, debes presentar el título oficial o resguardo de haberlo solicitado",
    p9: ". En el caso de que desees convalidar alegando haber cursado otro ciclo formativo, es suficiente con el certificado académico de notas y no es necesario que adjuntes también la copia del título o el resguardo de haberlo solicitado.",
    pBold10: "En el caso de alegar enseñanzas universitarias, además de la certificación académica oficial con indicación de las horas o créditos de cada materia superada, deberás presentar ",
    pBold11: "los programas de las asignaturas que haya cursado sellados ",
    pUnderline1: "(el sello debe ser original y no vale una fotocopia del programa en el que el sello no sea original) por el centro universitario",
    p10: ". Estos programas deben recoger la ",
    pBold12: "duración y contenidos teóricos y prácticos estudiados.",
    pBold13: "En el caso de alegar unidades de competencia oficialmente acreditadas, certificación oficial de la acreditación de la Unidad de Competencia o Certificado de profesionalidad expedido por la Administración Laboral competente, obtenido de acuerdo con lo establecido en el RD 34/2008, de 18 de enero.",
    pBold14: "Aunque ya se ha dicho anteriormente, se recuerda que ",
    pBold15: "todos los documentos (excepto el DNI y el documento de la solicitud de convalidación) tienen que ser original o copia compulsada",
    pBold16: ". ",
    pBold17: "También se recuerda que el centro no puede tramitar ante el Ministerio de Educación ninguna solicitud que no venga acompañada de la documentación establecida.",
    pBold18: "El solicitante deberá estar matriculado en los módulos profesionales que solicita convalidar y haber satisfecho los derechos de matrícula en las enseñanzas para las cuales solicita la convalidación.",
    pBold19: "Las convalidaciones entre estudios universitarios y de Formación Profesional se podrán solicitar cuando estos últimos pertenezcan al espacio de la educación superior",
    p11: ". Además, el número de módulos profesionales de los ciclos de grado superior convalidados ",
    pBold20: "no podrá superar el 60% de la totalidad de créditos ECTS",
    p12: " establecidos en el real decreto por el que se establece el título Técnico Superior y se fijan los aspectos básicos del currículo, siempre que se aporten ",
    pBold21: "enseñanzas universitarias que estén relacionadas con el campo de conocimiento y exista similitud entre las competencias, conocimientos y resultados de aprendizaje.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "OpenClipart-Vectors",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_6 = {
    titulo: "1.6.- ¿Cómo conseguir el programa de una asignatura universitaria?",
    p1: "Las convalidaciones ",
    pBold1: "basadas en una o varias asignaturas universitarias no se resuelven en el centro, solo se reciben y envían al Ministerio para su resolución",
    p2: ". La experiencia nos dice que debes respetar los requisitos establecidos por el Ministerio.",
    p3: "Además de la certificación académica oficial, el ",
    pBold2: "Ministerio exige que presentes los programas de las asignaturas sellados originalmente por la universidad. Este último requisito es indispensable. En caso de que no se envíen los programas sellados, no se podrá enviar la solicitud de convalidación. No importa si presentas el título universitario y el certificado:",
    p4: " sin programas sellados no hay convalidación.",
    p5: "¿Cómo conseguir los programas sellados? Es posible que hayas perdido los programas de cuando estudiaste en la Universidad, o si los tienes que no estén sellados, o en el peor de los casos, que ya no vivas ni siquiera donde estudiaste y no puedas desplazarte. Por eso no hay problema, siempre que tengas un poco de paciencia y quieras hacer lo que te proponemos, es muy probable que los consigas y puedas presentar tu solicitud de convalidación acompañada de los programas.",
    p6: "Para ello, sigue los siguientes pasos:",
    p7: "Haz una lista de las asignaturas relacionadas con el módulo que quieres convalidar.",
    p8: "Selecciona los departamentos responsables de esas asignaturas.",
    p9: "Entra en la web de la Universidad en la que estudiaste y busca los departamentos del apartado anterior. Localiza el teléfono del jefe/director del departamento y la dirección de correo.",
    p10: "Contacta por teléfono con el departamento y/o envía un correo con la siguiente información:",
    pItalic1: "Buenos días.",
    pItalic2: "Mi nombre es XXXX. Cursé la licenciatura/diplomatura/grado en XXX en la Facultad de XXXX Promoción 20XX-20XX y actualmente curso otros estudios para los que necesito el programa ",
    pBoldItalic1: "sellado",
    pItalic3: " por el centro universitario en cuestión de las siguientes asignaturas:",
    pItalic4: "XXXXX. curso, 20XX-20XX",
    pItalic5: "XXXXX. curso, 20XX-20XX",
    pItalic6: "Les agradecería si me pudiesen decir cómo conseguirlo o si me lo pudiesen enviar a la siguiente dirección: XXXX",
    pItalic7: "De no ser así, dígame cómo puedo hacerlo.",
    pItalic8: "De nuevo, gracias por su amabilidad.",
    pItalic9: "Saludos cordiales."
}

export const PAGE1_7 = {
    titulo: "1.7.- ¿Cómo saber si me convalidarán un módulo si he alegado estudios universitarios?",
    p1: "No se puede saber a priori.",
    p2: "Por eso el Ministerio de Educación y Formación Profesional solicita los programas universitarios sellados: para poder analizar caso a caso y de forma individualizada cada convalidación.",
    p3: "El Ministerio de Educación y Formación Profesional tiene en su página Web información sobre la convalidación de módulos profesionales aportando estudios universitarios. La podéis encontrar en este ",
    p4: "enlace",
    p5: "."
}

export const PAGE1_8 = {
    titulo: "1.8.- ¿Cuándo tendré noticias sobre si se ha aprobado la convalidación?",
    p1: "En primer lugar, hay que recordar que ",
    pBold1: "solo se pueden convalidar módulos en los que estás debidamente matriculado. La matrícula solo se da por finalizada cuando concluya el pago de las tasas",
    p2: ". Por tanto, hasta que el centro no tenga constancia del pago, no se podrá proceder a reconocer la convalidación. De esta forma, si el pago se retrasa cabría la posibilidad de que la resolución de la convalidación también se retrasara.",
    p3: "Si ",
    pBold2: "la convalidación la debe resolver el Ministerio, el plazo se alarga más, ya que",
    p4: " no se puede remitir la documentación a ese organismo hasta tener la constancia del pago realizado. En los últimos años, la resolución del Ministerio ha llegado bien entrado el año nuevo. ",
    pBold3: "Por eso es conveniente que presentes tu solicitud lo antes posible.",
    p5: " Una vez resuelta la convalidación, el Ministerio de Educación y Formación Profesional se pondrá directamente en contacto contigo, a través del correo electrónico que hayas facilitado en la solicitud de convalidación, para comunicarte el resultado y para que te descargues la resolución desde su Sede Electrónica. Si te han concedido la convalidación, deberás presentar la resolución en el centro para que la anoten en tu expediente académico. ",
    pBold4: "Es en este momento, y no antes, cuando tienes formalmente el módulo convalidado.",
    pBold5: "El Ministerio informa que se debe empezar a trabajar el módulo, con independencia de haber solicitado la convalidación, por si al llegar la resolución esta es negativa.  Durante el tiempo que el Ministerio informe al alumno/a de la resolución de la convalidación del módulo solicitado, es imprescindible que participe en las actividades a distancia (entrega de tareas, participación en foros, etc.) como obligación dentro del proceso de evaluación continua.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Webandi",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_9 = {
    titulo: "1.9.- ¿Qué efectos tendrá la convalidación en mi expediente?",
    p1: "Cada módulo profesional convalidado se recogerá en los documentos académicos, a efectos de cálculo de la nota media del ciclo formativo de Formación Profesional, con la calificación obtenida por el solicitante en el módulo profesional cursado que conste en la documentación académica correspondiente.",
    pBold1: "Los módulos profesionales convalidados con estudios universitarios, así como los que se convaliden aportando estudios anteriores a la LOGSE, unidades de competencia o certificación académica oficial de idioma no llevarán asignada ninguna puntuación",
    p2: ", constando en el expediente del alumnado como convalidado y no computarán a efectos de cálculo de la nota media del ciclo formativo.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "OpenClipart-Vectors",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_10 = {
    titulo: "1.10.- Enlaces relacionados",
    p1: "Además de los enlaces que han ido apareciendo a lo largo de este documento, en estos enlaces encontrarás más información sobre las convalidaciones en la Formación Profesional:",
    p2: "Información sobre ",
    pBold1: "convalidaciones en la página web de FP Andalucía.",
    p3: "Información sobre ",
    pBold2: "convalidaciones en la página web del Ministerio de Educación.",
    pBold3: "Normativa de apoyo",
    p4: " para las convalidaciones en FP.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Clker-Free-Vector-Images",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE2 = {
    titulo: "2.- Solicitud del título",
    p1: "Aquí encontrarás los pasos a seguir para solicitar el título del ciclo una vez hayas superado todos los módulos formativos que lo conforman.",
    p2: "Certificado"
}

export const PAGE2_1 = {
    titulo: "2.1.- Solicitud",
    p1: "Para solicitar el título ",
    pBold1: "deberás dirigirte al Centro docente donde finalizaste los estudios",
    p2: " conducentes a la obtención del título solicitado. Debe ser solicitados por los alumnos, previo pago de las tasas correspondientes.",
    p3: "Debes cumplimentar e imprimir el modelo 046 de autoliquidación de tasas de la Junta de Andalucía disponible en el siguiente enlace: ",
    p4: "Modelo 046",
    p5: ". En el apartado OBLIGADO AL PAGO, se deben cumplimentar los datos personales y de domiciliación del solicitante. En el apartado DATOS GENERALES, se debe marcar la casilla AUTOLIQUIDACIÓN. En el cuadro de texto situado debajo se indica el título que se solicita. Se escribirá la fecha en la que se va a realizar y la liquidación. En el código territorial pueden utilizarse los desplegables y seleccionar en código órgano territorial CONSEJERÍA DE EDUCACIÓN Y DEPORTE, en   Código provincia, la provincia donde se localice el centro y en Código centro, seleccionamos el centro donde superé el último módulo. En concepto de pago se indicará el código 0049 o bien se utilizará el desplegable y se seleccionará TASA POR EXPEDICIÓN DE TÍTULOS ACADÉMICOS Y PROFESIONALES.",
    p6: "Se valida el documento, y nos da la opción de imprimirlo para presentarlo en la entidad bancaria y pagar o bien realizar el pago telemático. El pago telemático requiere tener certificado digital.",
    p7: "El resto del documento será impreso mecánicamente por la entidad bancaria en el momento de realizar el ingreso si se opta por la impresión y presentación en la oficina bancaria.",
    p8: "Una vez realizado el pago, la entidad bancaria se queda con una de las copias del modelo (el talón de cargo); le entregará al solicitante el ejemplar para el interesado y el ejemplar para la Administración. El ejemplar para la Administración se lo quedará el centro docente.  El ejemplar para el interesado se lo devolverá el centro sellado,  sirviéndole de resguardo de solicitud.",
    p9: "Se remitirá al centro docente por correo postal (preferiblemente certificado con acuse de recibo) la siguiente documentación:",
    pBold2: "Fotocopia DNI por ambas caras.",
    pBold3: "Impreso de solicitud cumplimentado. ",
    p10: "Descargar impreso de solicitud ",
    p11: "(27155 B)",
    pBold4: "Impreso 046",
    p12: " (se debe enviar el ",
    pBold5: "ejemplar para la administración",
    p13: " y también el ",
    pBold6: "ejemplar para el interesado",
    p14: ", que se devolverá sellado por el centro como resguardo del título).",
    p15: "Si deseas recibir la certificación académica con todas las calificaciones obtenidas en el ciclo, has de comunicarlo cuando envíes todos los documentos al centro.",
    p16: "Ten en cuenta que la cantidad a ingresar la indica la Ley de Presupuesto de la Comunidad Autónoma de Andalucía que esté en vigor. Pregunta a tu tutor/a el importe que has de abonar teniendo en cuenta que los decimales has de escribirlos empleando la coma."
}

export const PAGE2_2 = {
    titulo: "2.2.- Tramitación y recogida",
    p1: "Cuando el centro en el que pides el título reciba la documentación, te devolverá el resguardo indicando que el título se encuentra en trámite. Resguardo que deberás guardar junto con el ejemplar para el interesado del impreso 046 hasta la llegada del título. Este puede tardar varios años en llegar al centro, será entonces cuando se te comunicará por correo que ya puedes recogerlo (también podrás recibirlo a través de las Delegaciones Territoriales).",
    p2: "Puedes encontrar más información al respecto:",
    p3: "En el artículo 7 de la ",
    p4: "ORDEN de 21 de mayo de 1996, por la que se regulan el procedimiento de expedición y la organización y funcionamiento del Registro de los títulos académicos y profesionales correspondientes a las enseñanzas establecidas por la Ley Orgánica 1/1990, de 3 de octubre, de Ordenación General del Sistema Educativo",
    p5: " y",
    p6: "En el ",
    p7: "Real Decreto 700/2019, de 29 de noviembre, por el que se modifica el Real Decreto 1850/2009, de 4 de diciembre, sobre expedición de títulos académicos y profesionales correspondientes a las enseñanzas establecidas por la Ley Orgánica 2/2006, de 3 de mayo, de Educación, para fijar el formato, el contenido y el soporte documental del Suplemento Europeo al Título de las Enseñanzas Artísticas.",
    imgLink1: " Scout ",
    imgLink2: "Happy Girl"
}

export const VERSION_RECORD = {
    titulo: "Historial de versiones",
    pBold1: "5.0 Actualización de enlaces en apartados 1.2, 1.27, 1.4, 1.5, 1.7, 1.10, 2.1 y 2.2. Actualización de texto en apartados: Introducción, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3,1.2.4, 1.2.7 (antiguo 1.2.6), 1.3, 1.4, 1.5, 1.7, 1.9, 2.1 y 2.2. Inclusión del apartado 1.2.6 que desplaza el antiguo a 1.2.7. Eliminación del apartado 1.8.1 (3/03/2022).",
    p1: "4.0 Actualización de enlaces en apartados 1.1.2, 1.5 y 1.10 (11/09/2020).",
    p2: "3.2. Modificación en el apartado 1.1. del plazo para recoger las solicitudes de convalidación. Revisión y restauración de enlaces (18/09/2019).",
    p3: '3.1. Modificación párrafo en apartado "2.1 Solicitud", para la entrega al centro del modelo 046 (25/01/2019).',
    p4: '3.0. Actualización del apartado "Convalidaciones en FP" ampliando la información al respecto en nuevos sub-apartados (10/10/2018).',
    p5: '2.0. Actualización de apartado "Solicitud del título" y su demostración. Creación de una primera sección sobre las convalidaciones (12/06/2017).',
    p6: '1.0. Versión inicial (16/04/2015).'
}