export const MENU = [
    "Información general: convalidaciones, exenciones y títulos",
    "1.- Solicitud de convalidaciones",
    "1.1.- Convalidaciones en FP",
    "1.1.1.- ¿Qué necesito para poder convalidar?",
    "1.1.2.- ¿Qué estudios puedo alegar?",
    "1.2.- ¿Dónde encontrar qué módulos son convalidables?",
    "1.2.1.- Condiciones para convalidar FOL",
    "1.2.2.- Condiciones para convalidar Empresa e Iniciativa Emprendedora",
    "1.2.3.- Condiciones para convalidar Inglés",
    "1.2.4.- Condiciones para convalidar Segunda Lengua Extranjera",
    "1.2.5.- Condiciones para convalidar las Horas de Libre Configuración",
    "1.2.6.- Condiciones para convalidar el módulo de Proyecto",
    "1.2.7.- Exención de la FCT",
    "1.3.- ¿Puedo convalidar un módulo acreditando experiencia laboral?",
    "1.4.- ¿Qué organismo resuelve las convalidaciones?",
    "1.5.- ¿Qué documentación debo enviar al centro?",
    "1.6.- ¿Cómo conseguir el programa de una asignatura universitaria?",
    "1.7.- ¿Cómo saber si me convalidarán un módulo si he alegado estudios universitarios?",
    "1.8.- ¿Cuándo tendré noticias sobre si se ha aprobado la convalidación?",
    "1.9.- ¿Qué efectos tendrá la convalidación en mi expediente?",
    "1.10.- Enlaces relacionados",
    "2.- Solicitud del título",
    "2.1.- Solicitud",
    "2.2.- Tramitación y recogida",
    "Historial de versiones",
]

export const HOME = {
    titulo: "Información general: convalidaciones, exenciones y títulos.",
    p1: "Antes de empezar debemos aclarar la diferencia entre convalidación, exención y traslado de calificación. La convalidación es el procedimiento por el cual se reconoce como superado un módulo que contiene los contenidos del módulo, módulos profesionales, asignatura o unidad de competencia que se aporta. La exención solo se aplica al módulo profesional de formación en centros de trabajo y se debe aportar una experiencia profesional acreditable y de duración definida. El traslado de calificaciones es la calificación que se asigna a un módulo que posee el mismo código y denominación que otro ya cursado y superado.",
    p2: "A continuación, se muestra información tutorial que esperamos que te sea de utilidad.",
    elaboradoTitulo: "Elaborado por:",
    elaboradoContenido: "Dirección General de Formación Profesional",
    versionTitulo: " Versión:",
    versionContenido: "5",
    fechaTitulo: "Fecha de publicación:",
    fechaContenido: "3/03/2022",
    imgLink1: "Woof ",
    imgLink2: " tutor and student"
}

export const PAGE1 = {
    titulo: "1.- Solicitud de convalidaciones",
    parrafo: "Aquí encontrarás información acerca de cómo solicitar la convalidación de un módulo profesional y la exención del módulo de Formación en Centros de Trabajo.",
    imgLink: "Balanza"
}

export const PAGE1_1 = {
    titulo: "1.1.- Convalidaciones en FP",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Claude star",
    imgLink5: " bajo ",
    imgLink6: "CC",
    parrafo1: "La Subdirección General de Ordenación e Innovación de la Formación Profesional del Ministerio de Educación y Formación Profesional, informa que ",
    parrafoBold1: "el plazo de presentación de solicitudes de convalidaciones de los alumnos en el centro se inicia el día que comienza el curso escolar y finaliza el último día del curso escolar.",
    parrafo2: " Tratándose con preferencia los expedientes presentados desde el inicio del plazo de matriculación hasta la finalización del mes de octubre.",
    parrafo3: "Este plazo es revisado de forma estricta por el Ministerio acogiéndose al Real Decreto 1085/2020, de 9 de diciembre, por el que se establecen convalidaciones de módulos profesionales de los títulos de Formación Profesional del sistema educativo español y las medidas para su aplicación, y se modifica el Real Decreto 1147/2011, de 29 de julio, por el que se establece la ordenación general de la formación profesional del sistema educativo, regula en su Capítulo II  el Procedimiento para las convalidaciones.",
    parrafo4: "Por todo ello, ",
    parrafoBold2: "os informamos a todas aquellas personas que deseen solicitar una convalidación que sea competencia del Ministerio de Educación que envíe la documentación en el plazo más breve de tiempo posible con el fin de comprobar la ausencia de errores y así poder iniciar el trámite lo antes posible.",
    parrafo5: "Las solicitudes de convalidaciones cuya resolución corresponden al director/a del centro docente donde esté matriculado el alumno se presentarán durante el mes de octubre.",
    parrafoBold3: "Solo se podrá presentar una única solicitud de convalidación por curso académico.",
    parrafoBold4: "ES MUY IMPORTANTE QUE TODA LA DOCUMENTACIÓN SEA CORRECTA Y ESTÉ COMPLETA."
}

export const PAGE1_1_1 = {
    titulo: "1.1.1.- ¿Qué necesito para poder convalidar?",
    parrafo1: "La primera condición:",
    parrafo2: "Si eres alumno de SEMI o distancia: ",
    parrafoBold1: "estar matriculado/a en el módulo que se desea convalidar",
    parrafo3: " y realizar el pago de las tasas correspondientes. Hasta que no se realice y se compruebe el pago, no se podrá ejecutar la convalidación en el expediente. De esta forma, si el pago se retrasa cabría la posibilidad de que la resolución de la convalidación también se retrasara.",
    parrafo4: "La ",
    parrafoBold2: "convalidación no se realiza sobre la globalidad del Título",
    parrafo5: " que se está cursando, sino sobre los módulos que se soliciten, si estos cumplen las condiciones para ello."
}

export const PAGE1_1_2 = {
    titulo: "1.1.2.- ¿Qué estudios puedo alegar?",
    parrafo1: "Para solicitar la convalidación de módulos profesionales de un ciclo formativo de FP ",
    parrafoBold1: "se pueden alegar enseñanzas",
    parrafo2: " cursadas dentro ",
    parrafoBold2: "del Sistema Educativo",
    parrafo3: " y Unidades de Competencia acreditadas. Por tanto, se puede aportar:",
    parrafoBold3: "Otros ciclos formativos",
    parrafo4: " de Formación Profesional de grado medio o superior cursados con anterioridad.",
    parrafoBold4: "Enseñanzas universitarias:",
    parrafo5: " diplomaturas, licenciaturas, grados.",
    parrafo6: "Las ",
    parrafoBold5: "antiguas enseñanzas de Formación Profesional",
    parrafo7: " de primer y segundo grado (títulos de Técnico auxiliar y Técnico especialista).",
    parrafo8: "Ciclos formativos de ",
    parrafoBold6: "Enseñanzas deportivas",
    parrafo9: " o de ",
    parrafoBold7: "Artes Plásticas y Diseño.",
    parrafo10: "Certificaciones académicas Oficiales de idioma (del mismo idioma que se solicita la convalidación y de nivel idóneo).",
    parrafo11: "Unidades de Competencia acreditadas.",
    parrafo12: "Las enseñanzas siguientes no se pueden alegar:",
    parrafoBold8: "Carnés profesionales y cursos de Formación Profesional para el empleo (FPO y FP continua)",
    parrafo13: ", distintos de los que conducen a la obtención de un ",
    parrafoItalic1: "Certificado de profesionalidad",
    parrafo14: " y a la acreditación oficial de unidades de competencia.",
    parrafoBold9: "Cursos privados",
    parrafo15: " realizados en academias y centros de formación que no imparten enseñanzas oficiales.",
    parrafoBold10: "Cursos propios impartidos en la Universidad",
    parrafo16: ", que no sean másteres oficiales como los cursos de experto, cursos de especialización, ...",
    parrafoBold11: "Títulos propios no oficiales de universidad.",
    parrafoBold12: "Certificados de idiomas no oficialmente aceptados.",
    parrafoBold13: "Experiencia laboral.",
    parrafoBold14: "Formación no formal.",
    parrafoBold15: "Titulaciones extranjeras homologadas.",
    parrafoBold16: "Títulos equivalentes LOGSE.",
    parrafoBold17: "Formaciones de otros ministerios que tienen concedida por normativa la equivalencia general o específica.",
    parrafo17: "Los ",
    parrafoBold18: "módulos profesionales",
    parrafo18: " que ",
    parrafoBold19: "hayan sido previamente convalidados no podrán ser alegados para convalidar.",
    parrafo19: " Solo se puede alegar materias que hayan sido cursadas y superadas. Los títulos extranjeros homologados tampoco podrán ser causa de una nueva convalidación con otros módulos profesionales.",
    parrafo20: "Los ",
    parrafoBold20: "estudios que tengan concedida la equivalencia específica o genérica ",
    parrafoBold21: "(aquí los tenéis)",
    parrafo21: ", a efectos académicos y/o profesionales, con títulos de Formación Profesional ",
    parrafoBold22: "no podrán ser utilizados a su vez para la convalidación de sus módulos profesionales",
    parrafo22: "; por tanto, quien haya superado la totalidad de un ciclo formativo LOGSE no podrá aportarlo para solicitar la convalidación de ningún módulo profesional del título LOE equivalente que lo sustituye. Las convalidaciones que aparecen recogidas en el anexo IV del Real Decreto que regula cada título están reservadas para quien no ha podido finalizar el ciclo formativo que se extingue y debe transitar al nuevo ciclo formativo equivalente, o para quien solicita dichas convalidaciones para un título diferente de aquel con el que se ha declarado la equivalencia.",
    parrafo23: "Haber cursado enseñanzas superiores no siempre da derecho a la convalidación de enseñanzas relacionadas, pero de menor nivel, aunque en ambas haya materias con nombres similares.",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "Escolaespai",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_2 = {
    titulo: "1.2.- ¿Dónde encontrar qué módulos son convalidables?",
    p1: "Son dos los documentos que debes consultar:",
    p2: "Por un lado, los diferentes ",
    pBold1: "Anexos del ",
    pBold2: "Real Decreto ",
    pItalic1: "1085/2020, de 9 de diciembre, por el que se establecen convalidaciones de módulos profesionales de los títulos de Formación Profesional del sistema educativo español y las medidas para su aplicación, y se modifica el Real Decreto 1147/2011, de 29 de julio, por el que se establece la ordenación general de la formación profesional del sistema educativo.",
    p3: " Aquí puedes consultar las tablas de convalidaciones del Real decreto 1085/2020, de 9 de diciembre (",
    p4: "tablas de convalidación",
    p5: ").",
    p6: "Por otro, el ",
    pBold3: "Anexo IV del Real Decreto",
    p7: " que crea el título LOE que estás estudiando, ya que establece las convalidaciones con módulos LOGSE del mismo Ciclo. Quien haya superado la totalidad de un ciclo formativo LOGSE no podrá aportarlo para solicitar la convalidación de ningún módulo profesional del ciclo formativo LOE que lo sustituye. Estas convalidaciones están reservadas para quien transita a un ciclo formativo LOE desde un ciclo formativo LOGSE, sin haberlo finalizado ni obtenido el título.",
    p8: "Ten en cuenta que los ",
    pBold4: "módulos profesionales con el mismo código y denominación",
    p9: " presentes en diferentes ciclos formativos LOE ",
    pBold5: "son en realidad el mismo módulo profesional.",
    p10: " Estos módulos se denominan ",
    pBold6: "transversales.",
    p11: " Si superas un módulo profesional transversal en un ciclo formativo, lo tendrás superado en cualquier otro del que también forme parte y ",
    pBold7: "la calificación obtenida se traslada de un ciclo al otro sin necesidad de convalidación ni más trámite.",
    p12: "Los módulos profesionales de FOL y EIE tienen en todos los ciclos formativos LOE la misma denominación, pero diferentes códigos. Por tanto, no hay arrastre de calificación sino convalidación. Se deben cursar o convalidar de un ciclo formativo a otro (siempre que se cumplan los requerimientos para ello).",
    p13: "La convalidación del módulo FOL puedes consultarla en el siguiente enlace: ",
    p14: "Convalidación de FOL",
    p15: ".",
    p16: "La convalidación del módulo EIE puedes consultarla en el siguiente enlace: ",
    p17: "Convalidación de EIE",
    p18: ".",
    imgLink1: "Imagen en ",
    imgLink2: "Pixabay",
    imgLink3: " de ",
    imgLink4: "MonikaP",
    imgLink5: " bajo ",
    imgLink6: "CC"
}

export const PAGE1_2_1 = {
    titulo: "1.2.1-. Condiciones para convalidar FOL",
    p1: "Para poder convalidar el módulo de FOL (Formación y Orientación Laboral) es necesario acreditar alguna de las siguientes condiciones:",
    p2: "Si el módulo a convalidar pertenece a un ciclo LOE (Ley Orgánica 2/2006, de 3 de mayo). ",
    pBold1: "Para esta convalidación es indiferente que los módulos que se aporten sean de grado medio o superior.",
    pBold2: "Tener aprobado el módulo de FOL en cualquier otro Ciclo LOE y acreditarlo documentalmente.",
    pBold3: "Tener aprobado el módulo de FOL en un Ciclo LOGSE (Ley Orgánica 1/1990, de 3 de octubre) y poseer un certificado que acredite que se posee la formación establecida para el desempeño de las funciones de nivel básico de la actividad preventiva",
    p3: " (PRL). Sirve cualquier curso de PRL impartido por alguna entidad legalmente constituida, de una duración no inferior a 30 horas y cuyos contenidos incluyan los que indica el anexo IV del Real Decreto 39/1997, de 17 de enero (BOE de 31 de enero de 1997), por el que se aprueba el Reglamento de los Servicios de Prevención. ",
    pBold4: "El certificado del curso de PRL deberá hacer constar específicamente tanto la duración como los contenidos impartidos.",
    pBold5: "Poseer el título de Técnico Superior en Prevención de Riesgos Profesionales derivado de la Ley Orgánica 1/1990, de 3 de octubre.",
    p4: "Si el módulo a convalidar pertenece a un ciclo LOGSE de grado medio (Ley Orgánica 1/1990, de 3 de octubre):",
    pBold6: "Tener aprobado el módulo de FOL en un Ciclo LOGSE (Ley Orgánica 1/1990, de 3 de octubre).",
    pBold7: "Tener aprobado el módulo de FOL en cualquier otro Ciclo LOE y acreditarlo documentalmente.",
    p5: "Si el módulo a convalidar pertenece a un ciclo LOGSE de grado superior (Ley Orgánica 1/1990, de 3 de octubre):",
    pBold8: "Tener aprobado el módulo de FOL en un Ciclo LOGSE de Grado Superior (Ley Orgánica 1/1990, de 3 de octubre).",
    table1: "Módulo a convalidar",
    table2: "Formación a aportar",
    table3: "FOL GM (LOGSE Ley Orgánica 1/1990, de 3 de octubre)",
    table4: "FOL GM LOGSE",
    table5: "FOL GS LOGSE",
    table6: "FOL GM LOE",
    table7: "FOL GS LOE",
    table8: "FOL GS (LOGSE Ley Orgánica 1/1990, de 3 de octubre)",
    table9: "FOL GS LOGSE",
    table10: "FOL GM (LOE Ley Orgánica 2/2006, de 3 de mayo)",
    table11: "FOL GM LOE",
    table12: "FOL GS LOE",
    table13: "FOL GM LOGSE + Certificado nivel básico actividad preventiva",
    table14: "FOL GS LOGSE + Certificado nivel básico actividad preventiva",
    table15: "Título Técnico Superior en Prevención de Riesgos Profesionales",
    table16: "FOL GS (LOE Ley Orgánica 2/2006, de 3 de mayo)",
    table17: "FOL GM LOE",
    table18: "FOL GS LOE",
    table19: "FOL GM LOGSE + Certificado nivel básico actividad preventiva",
    table20: "FOL GS LOGSE + Certificado nivel básico actividad preventiva",
    table21: "Título Técnico Superior en Prevención de Riesgos Profesionales"
}

export const PAGE1_2_2 = {
    titulo: "1.2.2.- Condiciones para convalidar Empresa e Iniciativa Emprendedora",
    p1: "Para poder convalidar el módulo de ",
    pBold1: "Empresa e Iniciativa Emprendedora",
    p2: " es necesario acreditar alguna de las siguientes condiciones:",
    p3: "Tener ",
    pBold2: "aprobado el módulo de Empresa e Iniciativa Emprendedora de otro ciclo formativo",
    p4: ", cualquiera que sea el grado, incluso en grados cruzados -medio o superior-.",
    p5: "Tener ",
    pBold3: "aprobado el módulo de Administración, gestión y comercialización en la pequeña empresa",
    p6: " (o con una denominación similar).",
    pBold4: "Poseer el Título de Técnico en Gestión administrativa o Técnico superior en Administración y finanzas.",
    table1: "Módulo a convalidar",
    table2: "Formación a aportar",
    table3: "Empresa e Iniciativa Emprendedora. (Cualquier ciclo formativo)",
    table4: "Administración, gestión y comercialización en la pequeña empresa. (Cualquier ciclo formativo)",
    table5: "Administración y gestión de un pequeño establecimiento comercial. Ciclo Comercio. (Comercio y Marketing)",
    table6: "Organización y gestión de una explotación agraria familiar Ciclo Trabajos Forestales y de Conservación del Medio Natural. (RD 1713/1996, de 12 de julio). (Agraria) Ciclo Jardinería. (RD 1714/1996, de 12 de julio). (Agraria) Ciclo Explotaciones Agrarias Extensivas. (RD 1715/1996, de 12 de julio) (Agraria) Ciclo Explotaciones Agrícolas Intensivas. (RD 1716/1996, de 12 de julio). (Agraria) Ciclo Explotaciones Ganaderas. (RD 1717/1996, de 12 de julio).  (Agraria)",
    table7: "Ciclo completo de Gestión administrativa. (RD 1662/1994, de 22 de julio). (Administración y Gestión)",
    table8: "Administración, gestión y comercialización en la pequeña empresa. (Cualquier ciclo formativo)",
    table9: "Organización y gestión de una pequeña empresa de actividades de tiempo libre y socioeducativas. Ciclo Animación Sociocultural. (Servicios Socioculturales y a la Comunidad) Ciclo Animación de Actividades Físicas y Deportivas. (Actividades Físicas y Deportivas) Ciclo Animación Turística. (Hostelería y Turismo)",
    table10: "Organización y control en agencias de viajes. Ciclo Agencias de Viajes. (Hostelería y Turismo)",
    table11: "Administración de establecimientos de restauración. Ciclo Restauración. (Hostelería y Turismo)",
    table12: "Administración y gestión de una unidad/gabinete de Ortoprotésica. Ciclo Ortoprotésica. (Sanidad)",
    table13: "Organización, administración y gestión de una unidad/gabinete de prótesis dentales. Ciclo Prótesis Dentales. (Sanidad)",
    table14: "Administración y gestión de un gabinete audioprotésico. Ciclo Audioprótesis. (Sanidad)",
    table15: "Organización y gestión de una empresa agraria. Ciclo Gestión y Organización de los Recursos Naturales y Paisajísticos. (Agraria) Ciclo Gestión y Organización de Empresas Agropecuarias. (Agraria)",
    table16: "Ciclo completo de Administración y finanzas. (RD 1659/1994, de 22 de julio). (Administración y Gestión)",
    table17: "Técnico en Gestión Administrativa LOE.  Ciclo completo",
    table18: "Técnico en Superior en Administración y Finanzas LOE. Ciclo completo",
    table19: "0402. Empresa e iniciativa emprendedora.",
    table20: "Gestión económico-administrativa en agencias de viajes. Organización y control en agencias de viajes.",
    table21: "0863. Empresa e iniciativa emprendedora.",
    table22: "Organización, administración y gestión de una unidad/gabinete de prótesis dentales.",
    table23: "Empresa e Iniciativa Emprendedora. (Cualquier ciclo formativo LOE)",
    table24: "Empresa e Iniciativa Emprendedora. (Cualquier ciclo formativo LOE)"
}